spring.application.name=springbootAmort
server.port=8080

# PostgreSQL local configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/amortisation_db
spring.datasource.username=postgres
spring.datasource.password=manage
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
